# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WAVFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/', validators=[webapp.models.validate_wav])),
                ('number', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
