# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wavfile',
            name='file',
            field=models.FileField(upload_to='.', validators=[webapp.models.validate_wav]),
        ),
        migrations.AlterField(
            model_name='wavfile',
            name='number',
            field=models.CharField(max_length=50, verbose_name='DID номер'),
        ),
    ]
